/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as RastrearRouteImport } from './routes/rastrear'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminTysonRouteImport } from './routes/admin-tyson'
import { Route as AdminPanelRouteImport } from './routes/admin-panel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminPanelIndexRouteImport } from './routes/admin-panel.index'
import { Route as ProductosSlugRouteImport } from './routes/productos.$slug'
import { Route as AdminPanelProductosRouteImport } from './routes/admin-panel.productos'
import { Route as AdminPanelPedidosRouteImport } from './routes/admin-panel.pedidos'
import { Route as AdminPanelCategoriasRouteImport } from './routes/admin-panel.categorias'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const RastrearRoute = RastrearRouteImport.update({
  id: '/rastrear',
  path: '/rastrear',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTysonRoute = AdminTysonRouteImport.update({
  id: '/admin-tyson',
  path: '/admin-tyson',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/admin-panel',
  path: '/admin-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelIndexRoute = AdminPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPanelRoute,
} as any)
const ProductosSlugRoute = ProductosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductosRoute,
} as any)
const AdminPanelProductosRoute = AdminPanelProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelPedidosRoute = AdminPanelPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminPanelRoute,
} as any)
const AdminPanelCategoriasRoute = AdminPanelCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminPanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRouteWithChildren
  '/admin-tyson': typeof AdminTysonRoute
  '/auth': typeof AuthRoute
  '/productos': typeof ProductosRouteWithChildren
  '/rastrear': typeof RastrearRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin-panel/categorias': typeof AdminPanelCategoriasRoute
  '/admin-panel/pedidos': typeof AdminPanelPedidosRoute
  '/admin-panel/productos': typeof AdminPanelProductosRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin-panel/': typeof AdminPanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-tyson': typeof AdminTysonRoute
  '/auth': typeof AuthRoute
  '/productos': typeof ProductosRouteWithChildren
  '/rastrear': typeof RastrearRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin-panel/categorias': typeof AdminPanelCategoriasRoute
  '/admin-panel/pedidos': typeof AdminPanelPedidosRoute
  '/admin-panel/productos': typeof AdminPanelProductosRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin-panel': typeof AdminPanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-panel': typeof AdminPanelRouteWithChildren
  '/admin-tyson': typeof AdminTysonRoute
  '/auth': typeof AuthRoute
  '/productos': typeof ProductosRouteWithChildren
  '/rastrear': typeof RastrearRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin-panel/categorias': typeof AdminPanelCategoriasRoute
  '/admin-panel/pedidos': typeof AdminPanelPedidosRoute
  '/admin-panel/productos': typeof AdminPanelProductosRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/admin-panel/': typeof AdminPanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-panel'
    | '/admin-tyson'
    | '/auth'
    | '/productos'
    | '/rastrear'
    | '/sobre-nosotros'
    | '/admin-panel/categorias'
    | '/admin-panel/pedidos'
    | '/admin-panel/productos'
    | '/productos/$slug'
    | '/admin-panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-tyson'
    | '/auth'
    | '/productos'
    | '/rastrear'
    | '/sobre-nosotros'
    | '/admin-panel/categorias'
    | '/admin-panel/pedidos'
    | '/admin-panel/productos'
    | '/productos/$slug'
    | '/admin-panel'
  id:
    | '__root__'
    | '/'
    | '/admin-panel'
    | '/admin-tyson'
    | '/auth'
    | '/productos'
    | '/rastrear'
    | '/sobre-nosotros'
    | '/admin-panel/categorias'
    | '/admin-panel/pedidos'
    | '/admin-panel/productos'
    | '/productos/$slug'
    | '/admin-panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminPanelRoute: typeof AdminPanelRouteWithChildren
  AdminTysonRoute: typeof AdminTysonRoute
  AuthRoute: typeof AuthRoute
  ProductosRoute: typeof ProductosRouteWithChildren
  RastrearRoute: typeof RastrearRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastrear': {
      id: '/rastrear'
      path: '/rastrear'
      fullPath: '/rastrear'
      preLoaderRoute: typeof RastrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-tyson': {
      id: '/admin-tyson'
      path: '/admin-tyson'
      fullPath: '/admin-tyson'
      preLoaderRoute: typeof AdminTysonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel': {
      id: '/admin-panel'
      path: '/admin-panel'
      fullPath: '/admin-panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel/': {
      id: '/admin-panel/'
      path: '/'
      fullPath: '/admin-panel/'
      preLoaderRoute: typeof AdminPanelIndexRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/productos/$slug': {
      id: '/productos/$slug'
      path: '/$slug'
      fullPath: '/productos/$slug'
      preLoaderRoute: typeof ProductosSlugRouteImport
      parentRoute: typeof ProductosRoute
    }
    '/admin-panel/productos': {
      id: '/admin-panel/productos'
      path: '/productos'
      fullPath: '/admin-panel/productos'
      preLoaderRoute: typeof AdminPanelProductosRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/pedidos': {
      id: '/admin-panel/pedidos'
      path: '/pedidos'
      fullPath: '/admin-panel/pedidos'
      preLoaderRoute: typeof AdminPanelPedidosRouteImport
      parentRoute: typeof AdminPanelRoute
    }
    '/admin-panel/categorias': {
      id: '/admin-panel/categorias'
      path: '/categorias'
      fullPath: '/admin-panel/categorias'
      preLoaderRoute: typeof AdminPanelCategoriasRouteImport
      parentRoute: typeof AdminPanelRoute
    }
  }
}

interface AdminPanelRouteChildren {
  AdminPanelCategoriasRoute: typeof AdminPanelCategoriasRoute
  AdminPanelPedidosRoute: typeof AdminPanelPedidosRoute
  AdminPanelProductosRoute: typeof AdminPanelProductosRoute
  AdminPanelIndexRoute: typeof AdminPanelIndexRoute
}

const AdminPanelRouteChildren: AdminPanelRouteChildren = {
  AdminPanelCategoriasRoute: AdminPanelCategoriasRoute,
  AdminPanelPedidosRoute: AdminPanelPedidosRoute,
  AdminPanelProductosRoute: AdminPanelProductosRoute,
  AdminPanelIndexRoute: AdminPanelIndexRoute,
}

const AdminPanelRouteWithChildren = AdminPanelRoute._addFileChildren(
  AdminPanelRouteChildren,
)

interface ProductosRouteChildren {
  ProductosSlugRoute: typeof ProductosSlugRoute
}

const ProductosRouteChildren: ProductosRouteChildren = {
  ProductosSlugRoute: ProductosSlugRoute,
}

const ProductosRouteWithChildren = ProductosRoute._addFileChildren(
  ProductosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminPanelRoute: AdminPanelRouteWithChildren,
  AdminTysonRoute: AdminTysonRoute,
  AuthRoute: AuthRoute,
  ProductosRoute: ProductosRouteWithChildren,
  RastrearRoute: RastrearRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
